blank_issues_enabled: true
contact_links:
  - name: ğŸ—’ï¸  nprint README
    url: https://github.com/nprint/nprintML#readme
    about: Consult the nprint README first.
  - name: ğŸ“– nPrint Usage Information
    url: https://nprint.github.io/nprint_walk.html
    about: Learn more about how to use nPrint here.
